In [15]:
import numpy as np

with open("input08.txt") as file:
    input = file.read().split()

trees_list = []
visible_trees = 0
for row in input:
    temp = []
    for letter in row:
        temp.append(letter)
    trees_list.append(temp)

trees_array = np.array(trees_list, dtype=int)
print(trees_array)

# visible_trees = 0
# for row in input:
#     for tree in row:
#         pass


[[0 1 1 ... 0 0 1]
 [1 0 2 ... 2 2 0]
 [0 0 2 ... 0 2 0]
 ...
 [1 2 2 ... 0 2 0]
 [2 2 1 ... 0 1 1]
 [2 0 2 ... 1 2 0]]


2